### PR TITLE
Update FS 2022

### PR DESCRIPTION
**Pull request by NaoPross**
I pretty much rewrote it from scratch

### CODE REVIEW

**Comment by lschmid** [comment]
Hi Nao,
Thanks a lot for contribute to the project. 

As you might have read the old license agreement, you are not allowed to remove previous contributors or change the license agreement. The contributors also need to be visible in the printed version.

But you are more then welcome to add your name to the contributors.

Happy learning and good luck with the exams.

**Comment by NaoPross** [comment]
Hi Lukas, I really didn't expect to hear from you since this document is about 10 years old.

Strictly speaking, I am allowed to [upgrade the CC license](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility) from version 3 to 4. Though actually, I don't really care, I just put the first complete text of the CC license I found online (I wouldn't change it to a non CC license).

I've put your name in there, though FYI there are already newer (similar) versions of this document on various places (shared cloud storage, studentenportal, etc.) that don't have your name on them. Besides, I rewrote the entire thing from scratch so I don't know how much "remixing" applies here, but I understand that desire to leave some kind of leagacy, so I'll leave your name.

Thanks for the wishes and have a nice day. Cheers.

**Comment by lschmid** [comment]
Hi Nao,
I just saw the email notification by pure luck/chance. I m normally not follow the PRs. 

I m aware that many might ignore the original authors wishes (FBraun and co.) to keep the contributors in the document. But never the less in the rare cases I check a PR I m looking for this. 

We (FBraun and Co) would very much appreciate if you could forward the information to the "Studentenvertreter" and ask them they should keep a eye on the contributors list. 

And about if you rewrote the entire thing, then I might actually be ok to be removed as the contributors. The other way would be to create a new repo for that. 
And I haven't checked actually the difference between V3 and V4 but yes, I assume it might be ok to update.

Have a nice day.

**Comment by NaoPross** [comment]
I guess you were from the generation that started all of this, which is a very cool. I appreciated your work.

Unfortunately I have to let you know that (I feel) the "LaTeX + Git Zusammenfassungen" community is slowly dying. AFAIK in the Bachelor I'm the last one that is keeping an eye on this stuff and I'm going to graduate this summer. In my year there wasn't much interest and the few who wrote something using LaTeX did not share their work here. I think it was already fading and the combination of the pandemic + the loss of identy with the fusion into OST (breakup of VSHSR) kinda killed it. I don't know how much the studenvertreter will care, but I'll let him know.

Maybe next year there will be a buch of new people that will be interested in continuing this work. I'll try to carve out some time and come back to Rappi in the fall to do [a presentation](https://github.com/openhsr/LaTeX-Workshop). I hope that will revive this a bit.

Cheers.

**Pull request merged**
